<?php
if(isset($succes_msg)){
    echo'<script>swal("'.$succes_msg.'","","succes");</script>';
}
if(isset($warning_msg)){
    echo'<script>swal("'.$warning_msg.'","","Warning");</script>';
}
if(isset($info_msg)){
    echo'<script>swal("'.$info_msg.'","","info");</script>';
}
if(isset($error_msg)){
    echo'<script>swal("'.$error_msg.'","","error");</script>';
}
?>